Create new branch
K414BIN/MetricManager pull request #1
Opened 2021-03-24 12:43 UTC by K414BIN

2021-03-24 12:58 UTC, Forkosigan requested changes

2021-03-24 12:58 UTC, Forkosigan commented on Controllers/CrudController.cs
> +            var listEnumerator = _holder.Values.GetEnumerator();
Лишнее. Зачем? Есть hold. Правда и именование hold непонятное. лучше что-то типа weatherForecast.

2021-03-24 12:58 UTC, Forkosigan commented on Controllers/CrudController.cs
> +                    return Ok(currentValue);
Мы должны вернуть список ВСЕХ элментов, которые попадают во временной интрвал

2021-03-24 12:58 UTC, Forkosigan commented on Controllers/CrudController.cs
> +
Лишняя пустая строка

2021-03-24 12:58 UTC, Forkosigan commented on Controllers/CrudController.cs
> +            foreach (var hold in _holder.Values)
hold -> weatherForecast

2021-03-24 12:58 UTC, Forkosigan commented on Controllers/CrudController.cs
> +            int  index = 0;
метод работает неправильно. Совершенно неясно почему он удаляет между двумя индексами. Нигде нет гарантии, что между этими индексами все даты попадают в заданный интервал

2021-03-24 13:27 UTC, K414BIN commented on Controllers/CrudController.cs
> +            int  index = 0;
Мне нужно было отсортировать List<WeatherForecast> по порядку и тогда такой метод заработал бы, но я не научился пользоваться способом индексирования типизированных пользователем массивов.

2021-03-24 13:39 UTC, K414BIN commented on Controllers/CrudController.cs
> +
Я удалил строку.

2021-03-24 13:40 UTC, K414BIN commented on Controllers/CrudController.cs
> +            foreach (var hold in _holder.Values)
Я переименовал переменную.

2021-03-24 13:53 UTC, K414BIN commented on Controllers/CrudController.cs
> +            int  index = 0;
Как отсортировать такой массив по дате через Enumerable или IEnumerable?

2021-03-24 13:54 UTC, K414BIN commented on Controllers/CrudController.cs
> +                    return Ok(currentValue);
Я решил эту проблему через новый List.

2021-03-24 13:54 UTC, K414BIN commented on Controllers/CrudController.cs
> +            var listEnumerator = _holder.Values.GetEnumerator();
Я все переименовал.

2021-03-24 20:23 UTC, Forkosigan commented on Controllers/CrudController.cs
> +            int  index = 0;
Зачем его вообще сортировать то? Чем вас не устраивает например такая реализация?
for(int i = _holder.Values; i>=0;i--)
{
    if (_holder.Values[i].Date>= firstDate && _hoder.Values[i].Date<=lastDate)
       _holder.Values.RemoveAt(i);
}

или вообще _holder.Values.RemoveAll(item => item.Date >= firstDate && item.Date <= lastDate)

2021-03-25 06:13 UTC, K414BIN commented on Controllers/CrudController.cs
> +            int  index = 0;
Я забыл поставить break, после нахождения первого совпадения.
Нельзя использовать Foreach для удаления в List<> (Remove или RemoveAt), потому что получаем вот эту ошибку:
Collection was modified; enumeration operation might not execute

Использовал последнюю строку и все получилось. Такая запись для меня в новинку. Буду использовать в дальнейшем.

2021-03-25 06:33 UTC, merged